### ISSUE TITLE
Exemple WalletKit Flutter Android (don't compile) 

### ISSUE THREAD

**Issue by ArthurBaradel-Sewlau** [reown-com/reown_flutter#59]
I have some problem to test the example of the raw configuration / file of wallet kit for android .
The same source work fine with ios.

I try to use the api 34 and 35 of android.

I use:
Releases AppKit-1.2.0
Reown_walletkit exemple
reown_flutter-AppKit-1.2.0\packages\reown_walletkit\example

My Flutter SDK: 3.22.3

![Capture d’écran 2024-12-16 à 15 25 58](https://github.com/user-attachments/assets/2a4a9d77-d8a0-4ed8-9a2d-4f62d35cdbd0)

Error:
![Capture d’écran 2024-12-16 à 15 31 29](https://github.com/user-attachments/assets/959ff444-d045-4683-bd10-696c377ceaed)

Do you have some idea ?
Path to consider:
Flutter version ?
Gradle Version ?
Java Version ?

What version do you use ?

**Comment by quetool** [comment]
Hello @ArthurBaradel-Sewlau, could you downgrade to Flutter 3.19 and check if works with that one? I'm updating our SDK to 3.24 this week.

**Comment by quetool** [comment]
Hello @ArthurBaradel-Sewlau, open `packages/reown_appkit/example/base/android/app/build.gradle` and comment out `signingConfigs`. This will fix it. Otherwise feel free to re-open.

**Comment by ArthurBaradel-Sewlau** [comment]
Hello, Thanks to application open now.
But I have an issue, the relay close the session with "reason:Unauthorized: origin not allowed."
Info:
I use the command: 
flutter run --dart-define="PROJECT_ID=MY-PROJECT-ID" --flavor internal 

Error:
![Capture d’écran 2024-12-17 à 16 45 08](https://github.com/user-attachments/assets/3df683dd-8cab-4c8d-9f10-de05cce91d08)

**Comment by quetool** [comment]
Do you have a projectId?

**Comment by ArthurBaradel-Sewlau** [comment]
Yes , i put it in MY-PROJECT-ID.
And it work for iOS.

**Comment by quetool** [comment]
Can you share your Dapp name so I can search for the projectId?

**Comment by ArthurBaradel-Sewlau** [comment]
Email for the account: it@sewlau.fr
Project Name: MobileApp
The ProjectID start with 88c...

**Comment by quetool** [comment]
The reason why is failing with "origin not allowed" is because you are running our sample wallet/dapp which already has an its own bundleId/packageName. So since you are whitelisting only your bundleId/packageName in your project for Android then it's failing. And that's also the reason why, on the other hand, it is working on iOS: because you are not whitelisting any bundleId/packageName there.

![Screenshot 2024-12-18 at 09 18 45](https://github.com/user-attachments/assets/3a550bd5-f375-4da8-8cf7-5e98018b388c)

So either you remove the whitelisted packageName for Android or you use your own packageName in your own wallet/dapp.

**Comment by quetool** [comment]
By the way, it seems like you marked your project as WalletKit for iOS. If this is not accurate, like if you are creating a Flutter Dapp, you should change that in order to get the proper updates when they come.

![Screenshot 2024-12-18 at 09 24 51](https://github.com/user-attachments/assets/78fddacb-ed30-42c9-aac3-be3217b61e20)
