### ISSUE TITLE
No internet connection error 

### ISSUE THREAD

**Issue by AmjadKhan2k18** [reown-com/reown_flutter#6]
**Describe the bug**
I have a phone for testing in which I can't turn on wifi or data, And I use cable to share internet from Computer while testing. 

So basically I have internet connection on this device but the Reown return error that i have no internet when `.connect` method is executed

```
ReownCoreError(code: -1, message: No internet connection, data: null)
```

**To Reproduce**
1. Turn off Wifi/data on your phone
2. Use cable to share internet to your phone from Computer
3. Connect to any Wallet

**Expected behavior**
User should be able to connect if Wifi/Data is off but have internet connection, we should check if user have internet not Wifi/Data

**Reproducible code**
```
final res = await wcClient!.reOwnSign.connect(
        optionalNamespaces: {
          'eip155': RequiredNamespace(
            chains: Web3Helper.getChains(wallet.web3Wallet),
            methods: Web3Helper.rpcOptionalMethods,
            events: Web3Helper.rpcEvents,
          ),
          // 'tron': RequiredNamespace(
          //   chains: [
          //     "tron:0x2b6653dc",
          //   ], // Ethereum chain/ Ethereum chain
          //   methods: ['tron_signTransaction', 'tron_signMessage'],
          //   events: [],
          // ),
        },
      );
```

**Smartphone (please complete the following information):**
 - Device: [e.g. Iphone X

**Comment by quetool** [comment]
Hello @AmjadKhan2k18, we use [connectivity_plus](https://pub.dev/packages/connectivity_plus) package to determine wether the device is connected or not and it seems like in your particular case (quite an edge case I'd say) this package can determine you are connected. I'll share your issue with the team but I really think you should ping **connectivity_plus** devs about this as it should be fixed in their side.

**Comment by quetool** [comment]
Hello @AmjadKhan2k18! We are gonna enhance this in the coming version. Are you still affected by this?
