### ISSUE TITLE
When release reown_appkit 1.3.0?

### ISSUE THREAD

**Issue by giantstar624** [reown-com/reown_flutter#68]
I'm now integrating reown_appkit for my flutter project. But latest stable version is 1.2.0 and it's buggy. Furthermore, it's using old version packages and causing conflicts in pub add. I hope you release 1.3.0 as soon as possible.

**Comment by quetool** [comment]
Hello @giantstar624! Any particular bug or conflict you want to report? Did you try 1.3.0-beta02?

https://pub.dev/packages/reown_appkit/versions/1.3.0-beta02

**Comment by giantstar624** [comment]
Thanks, @quetool . I've tried it and works fine. but there's another problem.
Google Sign-in isn't provided.
Also, QR Code option is not displayed on first screen. Need to click "All wallets".
![1](https://github.com/user-attachments/assets/d1f25df2-7bae-4fe3-96c9-ba5efac17a60)

**Comment by quetool** [comment]
Hello @giantstar624! None of them are problems, it's by design. Google option is yet not implemented on mobile SDKs and regarding the QR option not displayed in first screen, where did you see that? In the web (JS) SDK? Mobile SDKs are slightly different than Web. You can open a feature request and if we see this viable we could add it. Thanks!

**Comment by quetool** [comment]
Hello @giantstar624 , have you tried this?
You can completely skip first screen and directly open the QR code page by calling this:

```
appKitModal.openModalView(ReownAppKitModalQRCodePage());
```

Check here: https://docs.reown.com/appkit/flutter/core/usage#custom-buttons

Of course this would work only when a wallet is not connected yet.
